export const SEND_MULTIPLE_DATA_SUCCESS = 'SEND_MULTIPLE_DATA_SUCCESS';
export const SEND_MULTIPLE_DATA_ERROR = 'SEND_MULTIPLE_DATA_ERROR';

export const ADD_TRIP_REQUEST_MULTIPLE_DATA_SUCCESS = 'ADD_TRIP_REQUEST_MULTIPLE_DATA_SUCCESS';
export const ADD_TRIP_REQUEST_MULTIPLE_DATA_ERROR = 'ADD_TRIP_REQUEST_MULTIPLE_DATA_ERROR';

export const REMOVE_TRIP_REQUEST_MULTIPLE_DATA_SUCCESS = 'REMOVE_TRIP_REQUEST_MULTIPLE_DATA_SUCCESS';
export const REMOVE_TRIP_REQUEST_MULTIPLE_DATA_ERROR = 'REMOVE_TRIP_REQUEST_MULTIPLE_DATA_ERROR';
